packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
